"""empty message

Revision ID: 3d247a3e311b
Revises: 
Create Date: 2022-06-29 18:25:13.030504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d247a3e311b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('ganero', sa.String(length=16), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supermercado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade', sa.String(length=50), nullable=True),
    sa.Column('endereço', sa.String(length=100), nullable=True),
    sa.Column('receita', sa.Float(), nullable=True),
    sa.Column('lucro', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente_supermercado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.Integer(), nullable=True),
    sa.Column('supermercado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['supermercado'], ['supermercado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entregador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('genero', sa.String(length=16), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('supermercado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supermercado'], ['supermercado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('resolvido', sa.Boolean(), nullable=True),
    sa.Column('ajuda', sa.String(length=100), nullable=True),
    sa.Column('satisfação', sa.Integer(), nullable=True),
    sa.Column('cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('entregador', sa.Integer(), nullable=True),
    sa.Column('endereçõ', sa.String(length=100), nullable=True),
    sa.Column('cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['entregador'], ['entregador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrega_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrega', sa.Integer(), nullable=True),
    sa.Column('produto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entrega'], ['entrega.id'], ),
    sa.ForeignKeyConstraint(['produto'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrega_produto')
    op.drop_table('entrega')
    op.drop_table('suporte')
    op.drop_table('entregador')
    op.drop_table('cliente_supermercado')
    op.drop_table('supermercado')
    op.drop_table('produto')
    op.drop_table('cliente')
    # ### end Alembic commands ###
